org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.overridePathCheck=true
kotlin.incremental=false
kotlin.daemon.jvm.options=-Xmx768m
android.cxx.buildRoot=C:\\Users\\Administrator\\AppData\\Local\\Temp\\sengoku_cxx
